### ISSUE TITLE
NSubstitute version for EntityFrameworkCore 3.0.0

### ISSUE THREAD

**Issue by petrce** [rgvlee/EntityFrameworkCore.Testing#1]
Hi, 
I really like your library, 
can you please add NSubstitute support for EFCore 3?

**Comment by rgvlee** [comment]
Yes, this is possible.
It is a reasonable amount of work. Is there any specific functionality you are looking for that should be implemented first?

**Comment by petrce** [comment]
you are awesome :)

I am interested most in FromSqlInterpolated and ExecuteSqlInterpolated - because otherwise, I have to use quite ugly mocks

**Comment by rgvlee** [comment]
Heh, so everything :sweat_smile:
What is your timeframe? I'll kick it off this weekend.

**Comment by petrce** [comment]
no hurry, I can live a month with my ugly mocks, but I am happy to help with the beta testing

**Comment by rgvlee** [comment]
This feature can be tracked via the feature/AddEFCore3NSubSupport branch

**Comment by rgvlee** [comment]
Hey buddy, the RC is up

https://www.nuget.org/packages/EntityFrameworkCore.Testing.NSubstitute/2.0.3-RC02

I have a reasonably good set of tests so I don't anticipate any issues. Let me know how you go.

I've taken the opportunity to sync the interface between Moq and NSub versions... couple of ways you can create the db context mock:

The existing method
```
var dbContextToMock = new TestDbContext(new DbContextOptionsBuilder<TestDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);

var mockedDbContext = EntityFrameworkCore.Testing.NSubstitute.Create.MockedDbContextFor(dbContextToMock);
```

If your db context has a constructor with a single DbContextOptions<TDbContext> parameter you can just spec the type

```
var mockedDbContext = EntityFrameworkCore.Testing.NSubstitute.Create.MockedDbContextFor<TestDbContext>();
```

Finally there is a method that accepts a factory parameter

```
TestDbContext Factory()
{
    return new TestDbContext(new DbContextOptionsBuilder<TestDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
}

var mockedDbContext = EntityFrameworkCore.Testing.NSubstitute.Create.MockedDbContextUsingResultFrom(Factory);
```

I haven't documented the efcore 3 variants for the fromsql*/executesql* extensions in the readme yet but they are very similar and should be easy to work out.

Lastly, the executesql* extensions have an optional Action parameter that allows you to spec an operation/operations to perform after the executesql* invocation. So for example if your executesql* invokes a stored proc that deletes something, and your test asserts that deletion in some way, you can spec the behaviour. This went in the other week for work but I haven't had time to document it yet.

**Comment by petrce** [comment]
Hi, thanks for the effort! :) Just trying to use it in my project.

I tested FromSqlInterpolated, it works very well.

But do you know how to mock this using your helpers?
I made a virtual method `ExecuteSqlRawAsync` on DbContext to be able to mock it:
```
        public virtual async Task<int> ExecuteSqlRawAsync(string sql, params object[] parameters) => await Database.ExecuteSqlRawAsync(sql, parameters);
```
how can I do something like this using your helpers now?
```            
context.ExecuteSqlRawAsync(Arg.Any<string>(), Arg.Any<object[]>())
                .Returns(x =>
                {
                    ((SqlParameter)((object[])x[1])[6]).Value = matchId ?? DBNull.Value;
                    ((SqlParameter)((object[])x[1])[7]).Value = matchId == null ? "Pass" : "Not Pass";
                    return -1;
                });
```

**Comment by rgvlee** [comment]
Your existing mock is for any sql and for any parameters, so you could do 

```
var mockedDbContext = Create.MockedDbContextFor<YourContextType>();
mockedDbContext.AddExecuteSqlRawResult(-1);
```

that will get you the -1 expected result your current mock returns.

The sql parameters at position 6 and 7, are these output parameters from a stored proc? And this is expected behaviour you are trying to assert?
What is matchId, where is it coming from?

Currently the interface supports providing an action to perform post execution on something (i.e., a collection), but doesn't give you access to the sql/sql parameters provided to the method. I'd need to add another overload to do that.

Can you give me the rest of your test for context?

**Comment by petrce** [comment]
Exactly, it is for modifying output params coming from SPs. 

This is the simplest code I could create for you as an example. I believe SP does not need to exist to run the test:

Code:
```
public class MyService
{
 MyContext _context;

 public MyService(MyContext context){
  _context = context;
 }


 public string GiveMeCookie() {
  var outcomeParam = new SqlParameter("Outcome", SqlDbType.VarChar, 500) { Direction = ParameterDirection.Output };

  await _context.ExecuteSqlRawAsync(@"EXEC [GiveMeCookie] @Outcome = @Outcome OUT", outcomeParam);

  return outcomeParam.Value.ToString()
 }
}
```

DbContext method:
```
public class MyContext: DbContext
{
        public MyContext() {}

        public MyContext(DbContextOptions<MyContext> options) : base(options) {}

        protected MyContext(DbContextOptions options) : base(options) {}

  public virtual async Task<int> ExecuteSqlRawAsync(string sql, params object[] parameters) => await Database.ExecuteSqlRawAsync(sql, parameters);
}
```

Test method:
```
var context = Substitute.ForPartsOf<MyContext>();

context.ExecuteSqlRawAsync(Arg.Any<string>(), Arg.Any<object[]>())
                .Returns(x =>
                {
                    ((SqlParameter)((object[])x[1])[0]).Value = "Cookie";
                    return -1;
                });

var service = new MyService(context);

Assert.Equal(service.GiveMeCookie(), "Cookie");
```

**Comment by rgvlee** [comment]
I think this could be resolved by the AddExecuteSqlRawResult Action argument type being an Action\<CallInfo\> type, allowing your delegate function access to the nsub callinfo object. From there you could do whatever you want.
I haven't specifically tested a case like this but the theory seems sound.
I'll make/test that change tomorrow (getting a bit late here tonight)

**Comment by petrce** [comment]
yeah if you would allow me to access CallInfo using `Action<CallInfo>` it would be great, good night and thanks ;)

**Comment by rgvlee** [comment]
I have pushed RC03 which supports this behaviour

I opted to be a bit more verbose with the `Action<>` types to keep the interface the same between nsub and moq versions of the library. Rather than `Action<CallInfo>` I went with `Action<string, IEnumerable<object>>` with the string being the sql and the enumerable being the parameters that were provided by the ExecuteSql* invocation.

Efcore itself has a some variation in its interface across the ExecuteSql* stack between the Raw and Interpolated variants however at the end of the day we always end up with these two things. It's how I am doing the method matching in the library.

In terms of your usage, I would envisage something like this

```
public class MyService
{
    private readonly DbContext _context;

    public MyService(DbContext context)
    {
        _context = context;
    }

    public async Task<string> GiveMeCookie()
    {
        var outcomeParam = new SqlParameter("Outcome", SqlDbType.VarChar, 500) {Direction = ParameterDirection.Output};
        await _context.Database.ExecuteSqlRawAsync(@"EXEC [GiveMeCookie] @Outcome = @Outcome OUT", outcomeParam);
        return outcomeParam.Value.ToString();
    }
}

[Test]
public void GiveMeCookie_SetsOutputParameterValue()
{
    var mockedDbContext = Create.MockedDbContextFor<TestDbContext>();
    mockedDbContext.AddExecuteSqlRawResult(-1, (sql, parameters) =>
    {
        ((SqlParameter) parameters.ElementAt(0)).Value = "Cookie";
    });

    var service = new MyService(mockedDbContext);

    Assert.That(service.GiveMeCookie().Result, Is.EqualTo("Cookie"));
}
```

**Comment by petrce** [comment]
awesome job, tested, working

I have just a small suggestion to make the static Create class more NSubstitute(ish) (based on Substitute.ForPartsOf extension)
```
public static TDbContext MockedDbContextFor<TDbContext>(params object[] constructorArguments) where TDbContext : DbContext
{
            var dbContextToMock = (TDbContext) Activator.CreateInstance(typeof(TDbContext), options);
            return dbContextToMock.CreateMockedDbContext();
}
```

example of usage:
```
TestContext = Create.MockedDbContextFor<MyContext>(
                new DbContextOptionsBuilder<MyContext>()
                    .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString()).EnableSensitiveDataLogging()
                    .Options, Substitute.For<ITimeProvider>());
```

**Comment by rgvlee** [comment]
Ahh the dreaded parameterless constructor requirement for the substitute/mock creation.
I'd put this one off as I am not a huge fan of param object arrays but I can't really see a way around it that is intuitive. The substitute/mock need the constructor parameters if the DbContext doesn't have a parameterless constructor.

In RC05 I have extended Create.MockedDbContextFor<TDbContext>() to take params object array with the items being constructor arguments to create your DbContext.

```
[Test]
public void CreateMockedDbContextFor_ParametersForSpecificConstructor_CreatesSubstitute()
{
    var testContext = Create.MockedDbContextFor<MyContext>(
        new DbContextOptionsBuilder<MyContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).EnableSensitiveDataLogging().Options,
        Substitute.For<ITimeProvider>());

    Assert.Multiple(() =>
    {
        Assert.That(testContext, Is.Not.Null);
        Assert.That(ProxyUtil.IsProxy(testContext), Is.True);
    });
}
```

**Comment by petrce** [comment]
tested RC05, works great :)

**Comment by rgvlee** [comment]
1.0.6 (efcore 2) and 2.0.3 (efcore 3) have been released
I did some internal house keeping with regard to the Create factory interface change, and also ran into/resolved an issue with the IAsyncEnumerator/IAsyncEnumerable changes in .net core 3 that I hadn't come across til now.
Let me know of any issues
