### ISSUE TITLE
throwing exception for AddExecuteSqlRawResult

### ISSUE THREAD

**Issue by brandoq123** [rgvlee/EntityFrameworkCore.Testing#100]
Is there any way we can mock a thrown SqlException.

For example, in my code we have to run .ExecuteSqlRaw() for a stored proc. I was hoping to write a test on the behavior if that stored proc threw a SqlException to make sure my code is handling the exceptions properly.

I didn't see any options similar to Moq's option of .Setup().Throws() method on the .AddExecuteSqlRawResult() method.

**Comment by rgvlee** [comment]
I haven't included anything natively but there are a couple of ways you can do it right now.

Utilise the callback:

```C#
public class MyCustomException : Exception { }

[Test]
public void ExecuteSqlRaw_CallbackThrowsException_ThrowsException()
{
    MockedDbContext.AddExecuteSqlRawResult("sp_NoParams", default, (s, objects) => throw new MyCustomException());

    Assert.Throws<MyCustomException>(() =>
    {
        var actualResult = MockedDbContext.Database.ExecuteSqlRaw("sp_NoParams");
    });
}
```
The sql and parameter matching will work as expected. Alternatively you could extend the mock (Moq example provided, NSubstitute would be similar):

```C#
public class MyCustomException : Exception { }

[Test]
public void ExecuteSqlRaw_MockSetUpToThrowException_ThrowsException()
{
    var rawSqlCommandBuilderMock = Mock.Get(
        (
            (IRelationalDatabaseFacadeDependencies)
            (
                (IDatabaseFacadeDependenciesAccessor) MockedDbContext.Database).Dependencies
        )
        .RawSqlCommandBuilder
    );
    rawSqlCommandBuilderMock.Setup(m => m.Build(It.IsAny<string>(), It.IsAny<IEnumerable<object>>())).Throws<MyCustomException>();

    Assert.Throws<MyCustomException>(() =>
    {
        var actualResult = MockedDbContext.Database.ExecuteSqlRaw("sp_NoParams");
    });
}
```
This is just matching on any sql/parameter input, you'll have to set up the parameter matching yourself.

**Comment by rgvlee** [comment]
With a resolution provided, I'm closing this issue for now.
I'll add a feature request to make this a native part of the interface.
