### ISSUE TITLE
Mock SqlParameter

### ISSUE THREAD

**Issue by VincentDoreau13** [rgvlee/EntityFrameworkCore.Testing#102]
Hello,

I have a problem with the way of mocking the return on a stored procedure. Indeed I have an output parameter and would like to indicate this value to it during my test.

I am using version 3.x of your framework.

Here is the case that I reproduced in your tests :

```Csharp
[Test]
public void Test()
{
	var sql = "sp_WithOutput";
	var setUpParameters = new List<SqlParameter> {
		new()
		{
			ParameterName = "@id",
			SqlDbType = System.Data.SqlDbType.Int,
			Direction = System.Data.ParameterDirection.Output,
			Value = 125
		}
	};
	var invocationParameters = new List<SqlParameter> {
		new()
		{
			ParameterName = "@id",
			SqlDbType = System.Data.SqlDbType.Int,
			Direction = System.Data.ParameterDirection.Output
		}
	};
	var expectedResult = 1;
	AddExecuteSqlRawResult(MockedDbContext, sql, setUpParameters, expectedResult);

	var actualResult = MockedDbContext.Database.ExecuteSqlRaw($"[dbo].[sp_WithOutput] @id OUTPUT", invocationParameters);
}
```

**Comment by rgvlee** [comment]
What is the specific problem? Setting the value of the output parameter when `ExecuteSqlRaw` is invoked?
If that is the case, there is a test demonstrating how to do this [here](https://github.com/rgvlee/EntityFrameworkCore.Testing/blob/3.x/src/EntityFrameworkCore.Testing.Moq.Tests/Issue1Tests.cs).

**Comment by VincentDoreau13** [comment]
Hello,

Indeed, it works with me too. I had done my cast badly.
I think we should add an example in the README of the project
