### ISSUE TITLE
No support for BeginTransactionAsync in 3.x

### ISSUE THREAD

**Issue by digitaloc** [rgvlee/EntityFrameworkCore.Testing#126]
In my project, I am using EF core 5 and while testing a method that creates a transaction, BeginTransactionAsync(...) returns a null object. That results in an Exception when CommitAsync or RollbackAsync are called.

It seems that only BeginTransaction() is mocked:
https://github.com/rgvlee/EntityFrameworkCore.Testing/blob/1f0d88c5d41aabca2553b6f008af6c138b4223b9/src/EntityFrameworkCore.Testing.Moq/Helpers/MockedDbContextFactory.Internal.cs#L134

**Comment by jerone** [comment]
For anyone coming here to find a solution to above issue (for NSubstitute):

```c#
var mockedDbContextTransaction = Substitute.For<IDbContextTransaction>();
var mockedDbContext = Create.MockedDbContextFor<TestDbContext>();
mockedDbContext.Database.BeginTransaction().Returns(_ => mockedDbContextTransaction);
mockedDbContext.Database.BeginTransactionAsync()!.Returns(_ => mockedDbContextTransaction);
```

**Comment by rgvlee** [comment]
As mentioned this was pretty easy to work around, but support has been added to the respective LTS (v8.1.1) and STS (v9.0.0) versions.
I didn't get an issue with NSub, just the Moq version, even when I bumped the NSub dependency to latest. Same change/tests implemented regardless.

**Comment by jerone** [comment]
@rgvlee  Thanks for updating.

_For documentation purposes; corresponding commit: https://github.com/rgvlee/EntityFrameworkCore.Testing/commit/674219d0ee174eda313f200f67b84779da1d3a0b_
