### ISSUE TITLE
Object instance not created when mocking stored proc

### ISSUE THREAD

**Issue by KenBonny** [rgvlee/EntityFrameworkCore.Testing#135]
I'm trying to moq a call to a stored procedure, but when I try to set it up, I get this error.

Some code to reproduce:
``` csharp
public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }

    public DbSet<Data> Data { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Data>().HasNoKey();
    }
}

[Fact]
public async Task ThrowError()
{
    var context = Create.MockedDbContextFor<MyDbContext>();
    context.Data.AddFromSqlRawResult("MyStoredProc", new List<string>{ "a", "result" });

    const string sql = "dbo.MyStoredProc @Id = {0}";
    var result = await context.ArtikelCentraleEtiketData.FromSqlRaw(sql, 1).ToListAsync();
}
```

This produces the following error when I call `AddFromSqlRawResult`.

```
Object instance was not created by Moq. (Parameter 'mocked')
   at Moq.Mock.Get[T](T mocked) in C:\projects\moq4\src\Moq\Mock.cs:line 106
   at EntityFrameworkCore.Testing.Moq.Extensions.QueryProviderExtensions.AddFromSqlRawResult[T](IQueryProvider mockedQueryProvider, String sql, IEnumerable`1 parameters, IEnumerable`1 fromSqlResult)
   at EntityFrameworkCore.Testing.Moq.Extensions.QueryableExtensions.AddFromSqlRawResult[T](IQueryable`1 mockedQueryable, String sql, IEnumerable`1 fromSqlRawResult)
```

I'm not sure what else you need. So if you need additional information, I'll be happy to supply what you need. Maybe I did something wrong, but I can't figure out what.

**Comment by rgvlee** [comment]
Based on the sample and the error, I'd say the issue is that the DbSet is not marked as virtual (https://github.com/rgvlee/EntityFrameworkCore.Testing#virtual-setsqueries).
EFCore db first scaffolds the data model this way, so this avoids the 'changing the implementation for a test' argument.

**Comment by KenBonny** [comment]
That did indeed fix the issue. My apologies that I did not see this myself. Thank you for your time and help. 🙂
