### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by grosch-intl** [rgvlee/EntityFrameworkCore.Testing#142]
Looks like the nuspec for this is restricting to less than version 8 of .NET, which means I can't upgrade my code until you do.  I know .NET 8 just came out, but do you have an ETA?

Is there a specific reason this needs to disallow versions greater than .NET 7?

**Comment by rgvlee** [comment]
It's deliberate as the EFCore team usually makes breaking changes for the major releases.
I've run the tests over an upgrade to .NET 8/EFCore 8 and besides some error message changes the tests are passing.
I'll release a new version this weekend.

**Comment by rgvlee** [comment]
Pre release 8.0.0-rc01 is available for download. Let me know how you go.
I'll release 8.0.0 this week provided I don't see any issues. I wouldn't anticipate any, the upgrade was pretty straightforward.

**Comment by grosch-intl** [comment]
Thank you so much!  Just ran 160 unit tests after upgrading to .NET and only found 1 failure, which should have been hit after the upgrade.  :)
