### ISSUE TITLE
Dependency to Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by aberus** [rgvlee/EntityFrameworkCore.Testing#146]
I noticed we have a dependency on [`Microsoft.EntityFrameworkCore.SqlServer`](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/) NuGet package. 

Do we specifically require features unique to this package, or could it be replaced with [`Microsoft.EntityFrameworkCore.Relational`](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/)? 

Just trying to streamline no needed dependencies.

Thanks!

**Comment by aberus** [comment]
I create an example for NSubstitute [EntityFrameworkCore.Testing.NSubstitute.8.0.1.zip](https://github.com/rgvlee/EntityFrameworkCore.Testing/files/15235043/EntityFrameworkCore.Testing.NSubstitute.8.0.1.zip)

**Comment by rgvlee** [comment]
I've had a look and I believe you are correct, the Relational library should do the trick. Once I've verified support I'll release a new version.
I can't recall the decision to use the SqlServer library. Relational has been around forever by the looks of it so it's probably just a product of my own projects targeting SQL Server.

**Comment by rgvlee** [comment]
8.1.0-rc01 published, should be up soon. Will do the 8.1.0 release soon after.

**Comment by rgvlee** [comment]
8.1.0 released.
