### ISSUE TITLE
Performance on Create.MockedDbContextFor<TestDbContext>();

### ISSUE THREAD

**Issue by auserx** [rgvlee/EntityFrameworkCore.Testing#40]
Hello

it takes over 5 seconds to create the DbContext when running any of the create context methods like this one:

var mockedDbContext = Create.MockedDbContextFor<TestDbContext>();

Is this normal?

please note that my DbContext is not huge, it only has about 25 entities... 

I ran the tests in your project and it takes about 1 second maximum. I copied my DbContext over to your project and it also takes about 5 seconds or so.

**Comment by rgvlee** [comment]
I wouldn't consider that normal. I use the mocked db context for my projects at work and even on large db contexts with dozens of entities the tests complete in milliseconds.
As this project wraps over the MS in-memory provider by default, the first thing I would do is ascertain if that is the problem. How long does it take for something like the following to complete?

```C#
var options = new DbContextOptionsBuilder<TestDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;
var dbContext = new TestDbContext(options);
```

Obviously replace the type and use an appropriate constructor.

**Comment by auserx** [comment]
Hello and thanks for your quick response

I ran these 2 tests within your project using my DbContext which has 34 entities:

![image](https://user-images.githubusercontent.com/8115235/105461710-e2ca8780-5c8d-11eb-9cf6-e143964cc909.png)

![image](https://user-images.githubusercontent.com/8115235/105461759-eeb64980-5c8d-11eb-8909-f8c968673654.png)


As you can see the performance of Create.MockedDbContextFor<TestDbContext>(); is actually 14 seconds. I ran this test a few times to double check it wasn't a one off with similiar results...

I'd appreciate your help with this. Your library is exactly what we need and looks really good.

Thanks

**Comment by auserx** [comment]
I just ran another test with your DbContext and this is the result:

![image](https://user-images.githubusercontent.com/8115235/105463966-1c50c200-5c91-11eb-856f-0e0411cd9a6b.png)

**Comment by rgvlee** [comment]
I've run some quick tests using LINQPad, see this [gist](https://gist.github.com/rgvlee/5056728ad872a874b0ef5edf1e1c092c).

First execution:

![image](https://user-images.githubusercontent.com/47836784/105491013-9f553500-5cf0-11eb-9963-ea36984b03e9.png)

So it's taking 158 msec to create the db context itself. 827 the first time it's creating a mocked db context. Subsequent creations are pretty quick. Each block is creating a new in-memory database each time.

I get the following numbers on the next run

![image](https://user-images.githubusercontent.com/47836784/105491122-c9a6f280-5cf0-11eb-91b0-6a45362ac944.png)

Can you run the gist and report back your results.

**Comment by auserx** [comment]
Thank you for taking your time to test this.

Yes I have similar results using LINQPad:

**First run:**
199 msec elapsed
1131 msec elapsed
41 msec elapsed
30 msec elapsed

**Second run:**
0 msec elapsed
35 msec elapsed
27 msec elapsed
39 msec elapsed

Then I ran another test with the DbContext I'm using in my application which contains 34 entities and these are the results:

**1srt run:**
18 msec elapsed
6244 msec elapsed
306 msec elapsed
287 msec elapsed

**2nd run:**
0 msec elapsed
400 msec elapsed
267 msec elapsed
237 msec elapsed

As you can see, createing the mocked db context takes 6 seconds, which sort of indicates me that the bigger the db context, the longer it takes to create the mock

**Comment by rgvlee** [comment]
Thanks, I've been able to scale up the test db context and I'm seeing a rise in the time take to create the first db context mock.

At a guess it's probably a representation of the work that goes into creating a db set mock, all of which are set up automatically as part of the db context mock construction. Though they largely proxy over the underlying provider, there is still a lot of members to set up on each db set.

One solution may be to do just in time initialization of the db set mocks. What version are you using, and is this an issue you are experiencing for every test, or just the first one?

**Comment by auserx** [comment]
I'm using version 2.3.2

The main issue is with the first test, that in my case takes around 6 seconds. The tests that run after take around 800ms, which it's still a lot compared to using the InMemory dabatase directly that take around 50ms

So the performance hit is still very noticeable on every test.

**Comment by rgvlee** [comment]
I've released [2.3.3-beta05](https://www.nuget.org/packages/EntityFrameworkCore.Testing.Moq/2.3.3-beta05) which includes just in time set up for db sets and db queries.

For a db context with 30 entities, the initial creation takes about 500ms. Subsequent creations are < 10ms.

![image](https://user-images.githubusercontent.com/47836784/106080239-a85f5f80-6151-11eb-938e-00f4eef82dda.png)

![image](https://user-images.githubusercontent.com/47836784/106080273-b4e3b800-6151-11eb-8747-b4e03dc17b04.png)

This shifts the problem somewhat in that it's just not setting up entities that aren't used in the test so the actual improvement will vary. Regardless it does prove that Moq will support the just in time pattern for this scenario and should provide a decent performance improvement for most.

**Comment by auserx** [comment]
Nice one. This beta version contains a huge performance improvement. This is definitely working for us now.

To give you a real example, these are the times it takes to run all the tests in our project:

- Using the in memory database: 5 seconds
- Using version 2.3.2 of your library:  80 seconds
- Using version 2.3.3-beta05 of your library:  13 seconds

Now we don't need to use the mocked context for all our tests, only the ones that are going to benefit from it, so the final run will be way less than 13 seconds.

Good work - thanks so much for this. 

Now, do you need to create a new version of the library? Or is it ok to use this beta version?

Cheers

**Comment by rgvlee** [comment]
Good to hear. It's fine to use the beta for now. I'll release a 2.3.3 version soon.

**Comment by rgvlee** [comment]
Version 2.4.0 (for .NET Core 3.x/EFCore 3.x) has been released which includes this change among other optimizations. If I don't hear anything further I'll close this request soon.
