### ISSUE TITLE
Error starting test

### ISSUE THREAD

**Issue by JeanRasin** [rgvlee/EntityFrameworkCore.Testing#49]
Hello.

An error occurred while starting the test.
But when the test is run while debugging there is no error.

[link test](https://github.com/JeanRasin/SmartHouse/blob/master/Tests/TestRepository/GoalRepositoryTest.cs)

Tests - public void Create_Success() and public void Update_Success()

![Screenshot_1](https://user-images.githubusercontent.com/17027319/112482618-11ea9b80-8d9a-11eb-829d-1abf55205611.png)

**Comment by rgvlee** [comment]
Hi JeanRasin, this may be a side effect of a recent performance change. Previously I would set up the entire db context and all db sets on instantiation, however if the db context had many db sets this had an adverse affect on performance.

The way it works now is that db sets are set up on first access. At a guess it's not being accessed or recognised as being accessed and is therefore not setting up `DbContext.Entry<T>(entity)` on the mock. You could verify this behaviour using a method that will be set up regardless; `EntityState itemState = _mockedDbContext.Entry((object)_itemTestData).State;`

I'm working on another version at the moment so I'll see if I can repo and resolve the issue.

**Comment by rgvlee** [comment]
A fix for this issue will be included in the next release which shouldn't be too far away.

**Comment by rgvlee** [comment]
v4.0.0 (EFCore 6 preview 2), v3.0.1 (EFCore 5), v2.4.1 (EFCore 3) and v1.3.1 (EFCore 2.1.0+) have been released which includes a fix for this issue. Let me know if you have further issues.
