### ISSUE TITLE
Gettting Unsupported expression error when 

### ISSUE THREAD

**Issue by michaelakin** [rgvlee/EntityFrameworkCore.Testing#75]
System.NotSupportedException : Unsupported expression: <param> => <param>.Schedules
Non-overridable members (here: context.get_Schedules) may not be used in setup / verification expressions.
    
on this line:
`this.factorHeroContext.Set<Schedules>().AddFromSqlRawResult(schedules.AsQueryable());`

any ideas what I am doing wrong?

**Comment by rgvlee** [comment]
Hard to say exactly with the limited info at hand, but feels like your set is not marked virtual. An example of what is required is covered in the prerequisites section near the top of the readme.

**Comment by michaelakin** [comment]
That was is.  Thanks so much.

**Comment by michaelakin** [comment]
I do have another question.  It seems to keep the keep the context between tests even though I am creating the context for each test.

**Comment by michaelakin** [comment]
Never mind.  Apparently when using the in-memory database, you have to append something to the name of it to make it unique.

https://stackoverflow.com/a/54264857/98802

**Comment by rgvlee** [comment]
Yes, that is how the in-memory provider behaves. In the readme examples I use `Guid.NewGuid().ToString()` to provide a unique database name to avoid this issue.

The `Create.MockedDbContextFor<TDbContext>` method implicitly creates a db context to proxy over and uses a guid for the database name as well. Usage of the builder is generally for cases where you want to perform additional set ups on the mock (I do this for adjusting read only sets after SaveChanges is invoked on the db context) or to provide a different database provider like SQLite.
